name: Trivy Scan Image
on:
  workflow_call:
    inputs:
      image:
        description: Image to scan
        required: true
        type: string
jobs:
  build:
    name: CVE Image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.9.2
        with:
          image-ref: ${{ inputs.image }}
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
